version: '3.8'

services:
  vulnerable_service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./index.html:/var/www/html/index.html
      - ./index.php:/var/www/html/index.php
      - ./uploads.php:/var/www/html/uploads.php
      - ./.htaccess:/var/www/html/.htaccess
      - ./flag:/var/www/html/flag/
#      - ./uploads:/var/www/html/uploads
